[package]
name = "pigeonhole-blob"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "BlobBackend traits, rate limits, BootstrapPointer"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
foyer = { workspace = true }
futures = { workspace = true }
moka = { workspace = true }
pigeonhole-types = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
crc32fast = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
