#!/usr/bin/env bash
# Purge the real Discord backend + run the full client suite against it once.
#
# Requires DISCORD_BOT_TOKEN + discord channel_id in s3gram.toml (or .env).
# Build with: cargo build --release --features discord
#
# Usage:
#   ./scripts/compat-discord.sh
#   ./scripts/compat-discord.sh --all

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG="${S3GRAM_DC_LOG:-$ROOT/.cache/s3gram-discord.log}"
PIDFILE="${S3GRAM_DC_PID:-$ROOT/.cache/s3gram-discord.pid}"
REPORT="${S3GRAM_DC_REPORT:-$ROOT/.cache/discord-suite-report.txt}"

COMPAT_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --all) COMPAT_ARGS+=(--all); shift ;;
    --) shift; COMPAT_ARGS+=("$@"); break ;;
    *) COMPAT_ARGS+=("$1"); shift ;;
  esac
done

compat_sh() {
  if [[ ${#COMPAT_ARGS[@]} -eq 0 ]]; then
    ./scripts/compat.sh
  else
    ./scripts/compat.sh "${COMPAT_ARGS[@]}"
  fi
}

cd "$ROOT"
mkdir -p "$(dirname "$LOG")"

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi
: "${DISCORD_BOT_TOKEN:?DISCORD_BOT_TOKEN required in .env}"

CHANNEL_ID="${DISCORD_CHANNEL_ID:-}"
if [[ -z "$CHANNEL_ID" && -f s3gram.toml ]]; then
  CHANNEL_ID="$(sed -n 's/^channel_id[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' s3gram.toml | head -1)"
  if [[ -z "$CHANNEL_ID" ]]; then
    CHANNEL_ID="$(sed -n '/^\[discord\]/,/^\[/ s/^channel_id[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' s3gram.toml | head -1)"
  fi
  if [[ -z "$CHANNEL_ID" ]]; then
    CHANNEL_ID="$(sed -n 's/^chat_id[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' s3gram.toml | head -1)"
  fi
fi
: "${CHANNEL_ID:?discord channel_id required in s3gram.toml [discord] or chat_id}"

LISTEN_ADDR="${LISTEN_ADDR:-0.0.0.0:8333}"
PORT="${LISTEN_ADDR##*:}"
HOST_PORT="127.0.0.1:${PORT}"
ENDPOINT_URL="http://${HOST_PORT}"

cleanup() {
  if [[ -f "$PIDFILE" ]]; then
    kill "$(cat "$PIDFILE")" 2>/dev/null || true
    rm -f "$PIDFILE"
  fi
}
trap cleanup EXIT

source "$HOME/.cargo/env" 2>/dev/null || true

pass=0
fail=0
: >"$REPORT"
log_step() { echo "==> $*" | tee -a "$REPORT"; }
record() {
  local name="$1" rc="$2"
  if [[ "$rc" -eq 0 ]]; then
    echo "PASS  $name" | tee -a "$REPORT"
    pass=$((pass + 1))
  else
    echo "FAIL  $name (exit=$rc)" | tee -a "$REPORT"
    fail=$((fail + 1))
  fi
}

log_step "cargo test --workspace (discord crate uses wiremock only)"
set +e
cargo test -p s3gram-discord 2>&1 | tee -a "$REPORT"
record "cargo test -p s3gram-discord" "${PIPESTATUS[0]}"
set -e

log_step "build release (features discord)"
cargo build --release --features discord -q

if lsof -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; then
  echo "port $PORT busy; stop the existing server before compat-discord" >&2
  exit 1
fi

CFG="$ROOT/.cache/s3gram-discord-config.toml"
DB_URL="sqlite:s3gram.db"
if [[ -f s3gram.toml ]]; then
  parsed="$(sed -n 's/^database_url[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' s3gram.toml | head -1 || true)"
  [[ -n "$parsed" ]] && DB_URL="$parsed"
fi

cat >"$CFG" <<EOF
# generated by scripts/compat-discord.sh
listen_addr = "${LISTEN_ADDR}"
database_url = "${DB_URL}"
region = "us-east-1"
memory = false

[backend]
kind = "discord"

[discord]
channel_id = "${CHANNEL_ID}"

[snapshot]
interval_secs = 0

[chunk]
size = 19922944
codec = "zstd"
frame_size = 1048576

[ingest]
memory_budget = 268435456

[telegram]
send_rate_per_sec = 0.5
send_burst = 3.0
get_file_rate_per_sec = 15.0
get_file_burst = 30.0
delete_rate_per_sec = 1.0
delete_burst = 5.0
upload_concurrency = 2
download_concurrency = 8
EOF

export S3GRAM_CONFIG="$CFG"
export DISCORD_BOT_TOKEN

export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-s3gram}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-s3gramsecret}"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export AWS_REGION="${AWS_REGION:-$AWS_DEFAULT_REGION}"
export AWS_ENDPOINT_URL="$ENDPOINT_URL"
export AWS_EC2_METADATA_DISABLED=1
export AWS_CONFIG_FILE=/dev/null
export AWS_SHARED_CREDENTIALS_FILE=/dev/null
export S3GRAM_HOST=127.0.0.1
export S3GRAM_PORT="$PORT"
export ENDPOINT="$ENDPOINT_URL"

./target/release/s3gram >"$LOG" 2>&1 &
echo $! >"$PIDFILE"

for _ in $(seq 1 80); do
  code="$(curl -s -o /dev/null -w '%{http_code}' "$ENDPOINT_URL/" || true)"
  if [[ -n "$code" && "$code" != "000" ]]; then
    break
  fi
  sleep 0.15
done
if [[ -z "${code:-}" || "$code" == "000" ]]; then
  echo "discord server failed to start; see $LOG" >&2
  exit 1
fi
log_step "s3gram DiscordBlobStore listening on $ENDPOINT_URL (pid $(cat "$PIDFILE"))"

log_step "smoke"
set +e
./scripts/smoke.sh 2>&1 | tee -a "$REPORT"
record "smoke" "${PIPESTATUS[0]}"
set -e

log_step "compat.sh"
set +e
compat_sh 2>&1 | tee -a "$REPORT"
record "compat/s3-tests" "${PIPESTATUS[0]}"
set -e

echo | tee -a "$REPORT"
echo "======== summary ========" | tee -a "$REPORT"
echo "pass=$pass fail=$fail" | tee -a "$REPORT"
echo "log: $LOG" | tee -a "$REPORT"
echo "report: $REPORT" | tee -a "$REPORT"

if [[ "$fail" -ne 0 ]]; then
  exit 1
fi
echo "discord suite OK"
