#!/usr/bin/env bash
# Write a temporary s3gram.toml for compat / CI runs.
# Usage: source this after setting vars, or call:
#   CONFIG_OUT=... ./scripts/gen-config.sh
#
# Recognized env (all optional except where noted):
#   CONFIG_OUT          output path (required)
#   CONFIG_MEMORY       true|false (default false)
#   CONFIG_CHAT_ID      telegram chat id (required when memory=false)
#   CONFIG_LISTEN_ADDR  default 0.0.0.0:8333
#   CONFIG_DATABASE_URL default sqlite:s3gram.db / memory variant
#   CONFIG_REGION       default us-east-1
#   CONFIG_SNAPSHOT_SECS default 300 (0 for memory suites)
#   CONFIG_CHUNK_SIZE   default 19922944
#   CONFIG_CHUNK_CODEC  default zstd

set -euo pipefail

: "${CONFIG_OUT:?CONFIG_OUT required}"

MEMORY="${CONFIG_MEMORY:-false}"
LISTEN_ADDR="${CONFIG_LISTEN_ADDR:-0.0.0.0:8333}"
REGION="${CONFIG_REGION:-us-east-1}"
CHUNK_SIZE="${CONFIG_CHUNK_SIZE:-19922944}"
CHUNK_CODEC="${CONFIG_CHUNK_CODEC:-zstd}"

if [[ "$MEMORY" == "true" || "$MEMORY" == "1" ]]; then
  SNAPSHOT_SECS="${CONFIG_SNAPSHOT_SECS:-0}"
  DATABASE_URL="${CONFIG_DATABASE_URL:-sqlite:s3gram-memory.db}"
  CHAT_LINE=""
else
  SNAPSHOT_SECS="${CONFIG_SNAPSHOT_SECS:-300}"
  DATABASE_URL="${CONFIG_DATABASE_URL:-sqlite:s3gram.db}"
  : "${CONFIG_CHAT_ID:?CONFIG_CHAT_ID required when memory=false}"
  CHAT_LINE="chat_id = \"${CONFIG_CHAT_ID}\""
fi

mkdir -p "$(dirname "$CONFIG_OUT")"
cat >"$CONFIG_OUT" <<EOF
# generated by scripts/gen-config.sh — do not edit
${CHAT_LINE}
listen_addr = "${LISTEN_ADDR}"
database_url = "${DATABASE_URL}"
region = "${REGION}"
memory = ${MEMORY}

[snapshot]
interval_secs = ${SNAPSHOT_SECS}

[chunk]
size = ${CHUNK_SIZE}
codec = "${CHUNK_CODEC}"
frame_size = 1048576

[ingest]
memory_budget = 268435456

[telegram]
send_rate_per_sec = 0.5
send_burst = 3.0
get_file_rate_per_sec = 15.0
get_file_burst = 30.0
delete_rate_per_sec = 1.0
delete_burst = 5.0
upload_concurrency = 2
download_concurrency = 8
EOF
