[package]
name = "s3gram"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[[bin]]
name = "s3gram"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
dotenvy = { workspace = true }
http = { workspace = true }
s3s = { workspace = true }
serde_json = { workspace = true }
s3gram-blob = { workspace = true }
s3gram-core = { workspace = true }
s3gram-chunk = { workspace = true }
s3gram-engine = { workspace = true }
s3gram-index = { workspace = true }
s3gram-s3 = { workspace = true }
s3gram-telegram = { workspace = true }
s3gram-discord = { workspace = true, optional = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = []
discord = ["dep:s3gram-discord"]

[dev-dependencies]
bytes = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
s3s = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[lib]
name = "s3gram"
path = "src/lib.rs"
